version = 0.1
[default.deploy.parameters]
stack_name = "tabapay"
resolve_s3 = true
s3_prefix = "tabapay"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"v0\""
image_repositories = []
